### PR TITLE
Updating float64, copyright year, and package name

### PR DESCRIPTION
**Pull request by markbennett95**
yeeee

### CODE REVIEW

**Comment by martinholters** [comment]
Note that these changes will likely have a severe performance impact. If your intend is to also support, say, `Float32` as a data type for all the computations, it would probably be better to introduce a type variable to all the `struct`s and then use that instead of `Float64` (or `Real`). That would also be something I could imagine merging here.

**Comment by markbennett95** [comment]
Hey Martin,

I’m trying to make an ACME-created state space model of which I can calculate the gradient using e.g. ForwardDiff.jl. Currently this is not possible as packages such as forwardDiff require functions to be defined generally enough such that data of type ForwardDiff.Dual() can be passed through them (which I believe requires functions to accept T<:Real, and not make calls to BLAS), and several matrices within ACME are hard-coded as  either BigInt or Float64. I was hoping that broadening these typedef’s would allow me to calculate the gradient without changing the behaviour too much, but so far I’ve been unsuccessful.

If you had any ideas on how I can proceed, I’d love to hear from you. This is for my master’s thesis and this snag is really stalling my progress.

Thanks!!

Mark

From: Martin Holters ***@***.***>
Reply-To: "HSU-ANT/ACME.jl" ***@***.***>
Date: Monday, June 7, 2021 at 5:06 AM
To: "HSU-ANT/ACME.jl" ***@***.***>
Cc: Mark Bennett ***@***.***>, State change ***@***.***>
Subject: Re: [HSU-ANT/ACME.jl] Updating float64, copyright year, and package name (#55)


Note that these changes will likely have a severe performance impact. If your intend is to also support, say, Float32 as a data type for all the computations, it would probably be better to introduce a type variable to all the structs and then use that instead of Float64 (or Real). That would also be something I could imagine merging here.

**Comment by martinholters** [comment]
I see. Even if you can sufficiently relax the types, I guess ForwardDiff will have a hard time with the Newton solver due to its iterative nature. But taking derivatives of the linear part is trivial and taking derivatives of the nonlinear part is aided by the fact that the Jacobian of the function defining the nonlinear equation can be computed. 
For example, if you have a `model` with only one nonlinear system (i.e. not decomposed), the state `model.x` is set up as desired and `u` holds the desired input (as a vector, even if 1-dimensional), then
```julia
p = model.dqs[1]*model.x+model.eqs[1]*u
z = ACME.solve(model.solvers[1], p)
res = zeros(ACME.nn(model))
Jq = zeros(ACME.nn(model),ACME.nq(model,1))
model.nonlinear_eq_funcs[1](res, zeros(ACME.nn(model),ACME.nn(model)), model.pexps[1]*p, Jq, model.fqs[1], z)
dy_du = model.ey - model.fy/(Jq*model.fqs[1])*Jq*model.pexps[1]*model.eqs[1]
```
gives the derivative of output with respect to input at the point `(model.x, u)`. (I'm not exactly clear on what gradient you're after.) 

Yes, this involves a lot of undocumented internals, but if you confirm that this goes into the right direction, we could think of how to incorporate this properly in ACME.

**Comment by markbennett95** [comment]
Thank you, that’s very helpful!

I’m trying to do parameter optimization, like the paper that yourself and Holmes published in 2017. I’m trying to calculate the gradient of a state space model w.r.t. a parameter set P (that i.e. contains parameters of a BJT, or the value of a resistor) such that an optimization algorithm can be used to match the model’s behaviour to a set of measured data, so not necessarily the gradient w.r.t the voltage/current input(s). Ideally what I’d like to be able to do is define a function similar in nature to the superover() example, which has input arguments for the drive, tone, and level controls, and calculate the gradient w.r.t  those inputs.

I know that there are gradient-free optimization algorithms but they’ve given me mixed results thus far, and often don’t allow for bounded optimization. After playing around for a few days, I don’t think relaxing the type definitions in ACME sufficiently to allow generalized gradient calculation is going to be as straightforward as I’d hoped, given that I’d also need to replace the BLAS functions used for matrix multiplication. Do you think it’d be possible to accomplish what I’m after using a similar method to what you described? My inclination is no, because the Jacobian of the N-L functions is likely calculated w.r.t the inputs. Any ideas/thoughts are greatly appreciated!!

Mark

From: Martin Holters ***@***.***>
Reply-To: "HSU-ANT/ACME.jl" ***@***.***>
Date: Monday, June 7, 2021 at 11:10 AM
To: "HSU-ANT/ACME.jl" ***@***.***>
Cc: Mark Bennett ***@***.***>, State change ***@***.***>
Subject: Re: [HSU-ANT/ACME.jl] Updating float64, copyright year, and package name (#55)


I see. Even if you can sufficiently relax the types, I guess ForwardDiff will have a hard time with the Newton solver due to its iterative nature. But taking derivatives of the linear part is trivial and taking derivatives of the nonlinear part is aided by the fact that the Jacobian of the function defining the nonlinear equation can be computed.
For example, if you have a model with only one nonlinear system (i.e. not decomposed), the state model.x is set up as desired and u holds the desired input (as a vector, even if 1-dimensional), then

p = model.dqs[1]*model.x+model.eqs[1]*u

z = ACME.solve(model.solvers[1], p)

res = zeros(ACME.nn(model))

Jq = zeros(ACME.nn(model),ACME.nq(model,1))

model.nonlinear_eq_funcs[1](res, zeros(ACME.nn(model),ACME.nn(model)), model.pexps[1]*p, Jq, model.fqs[1], z)

dy_du = model.ey - model.fy/(Jq*model.fqs[1])*Jq*model.pexps[1]*model.eqs[1]

gives the derivative of output with respect to input at the point (model.x, u). (I'm not exactly clear on what gradient you're after.)

Yes, this involves a lot of undocumented internals, but if you confirm that this goes into the right direction, we could think of how to incorporate this properly in ACME.

**Comment by martinholters** [comment]
If the parameter is a resistance, it is basically what I proposed above if you use a potentiometer: The potentiometer setting is exposed like any other circuit input. You could just ignore the derivative of the actual (voltage) input signal or use a fixed voltage source instead. If you want to optimize the parameters of a stateful system for a whole input signal things get trickier though, as the output at time n depends also on the states from time n-1 which in turn themselves depend on the parameter(s) (and earlier states still), so you would need to also compute the derivative of the states (wrt the parameters) and then apply the chain rule to propagate along time, I guess. Probably error-prone to get right but should be doable. For optimizing the parameter of a BJT, say, you could modify the BJT model to expose that parameter as an input and proceed as before.

One word of caution: The handling of these parameters within ACME might be far from optimal; they inflate the nonlinear system and hence increase runtime and might even cause convergence issues. I'm therefore not sure whether optimization of more than just a few parameters at once is practical with this approach.

**Comment by markbennett95** [comment]
Thanks again for the info! The models I’m trying to optimize are simple two voltage sources and a BJT, so they should be memoryless and not evolve over time. Using gradient-free methods I have been able to get an optimization algorithms to converge for models with 5 parameters, and I think that’s going to be my best bet. A generalized method of finding the gradient for such (potentially) complex systems with many parameters just isn’t a problem I’m able to tackle I don’t think.

I’m going to exhaust my options for gradient-free optimization algorithms which will hopefully get me a decent result. In future, though, if there’s interest in implementing a similar feature into ACME for the purpose of determining Component sensitivity in a circuit, id definitely be interested in getting involved.

Thanks again, for this exchange and for the rest of your publications which have been extremely helpful to me!

Mark

From: Martin Holters ***@***.***>
Reply-To: "HSU-ANT/ACME.jl" ***@***.***>
Date: Tuesday, June 8, 2021 at 7:57 AM
To: "HSU-ANT/ACME.jl" ***@***.***>
Cc: Mark Bennett ***@***.***>, State change ***@***.***>
Subject: Re: [HSU-ANT/ACME.jl] Updating float64, copyright year, and package name (#55)


If the parameter is a resistance, it is basically what I proposed above if you use a potentiometer: The potentiometer setting is exposed like any other circuit input. You could just ignore the derivative of the actual (voltage) input signal or use a fixed voltage source instead. If you want to optimize the parameters of a stateful system for a whole input signal things get trickier though, as the output at time n depends also on the states from time n-1 which in turn themselves depend on the parameter(s) (and earlier states still), so you would need to also compute the derivative of the states (wrt the parameters) and then apply the chain rule to propagate along time, I guess. Probably error-prone to get right but should be doable. For optimizing the parameter of a BJT, say, you could modify the BJT model to expose that parameter as an input and proceed as before.

One word of caution: The handling of these parameters within ACME might be far from optimal; they inflate the nonlinear system and hence increase runtime and might even cause convergence issues. I'm therefore not sure whether optimization of more than just a few parameters at once is practical with this approach.

**Pull request closed without merging**
